INSERT INTO `mini`.`song` (`id`, `artist`, `track`, `link`, `year`, `country`, `genre`) VALUES
(1, 'Dirty Dike', 'How many dikes', 'https://www.youtube.com/watch?v=NDw8sl7PL8w', '2013', 'UK', 'Rap'),
(2, 'Chancha via Circuito & JosÃ© Larralde', 'Quimey Neuquen', 'https://www.youtube.com/watch?v=yJGL1hdl8Cw', '2010', 'Argentina', 'Dub'),
(3, 'Farhot', 'Represent Heart', 'https://www.youtube.com/watch?v=Y-73_uhtkr8', '2014', 'Germany', 'Rap / Instrumental HipHop'),
(4, 'Romare', 'Jimi & Faye (Part One)', 'https://www.youtube.com/watch?v=9BNwt8Q_7qw', '2013', 'UK', 'Instrumental HipHop / Dub / Sampling'),
(5, 'Gibmafuffi', 'Trinkhallenromantik (feat. DÃ¶ll)', 'https://www.youtube.com/watch?v=bi_aa2j9N-g', '2014', 'Germany', 'Rap'),
(6, 'Allie X', 'Bitch', 'https://www.youtube.com/watch?v=l3K1UlEaVGw', '2014', 'Canada', 'Electro / 8bit / Drone-Punk / Crystal Castles'),
(7, 'GrÃ¼nbox', 'Papone di Rey (feat. Teeny & Victor Magro)', 'https://soundcloud.com/grunbox/grunbox-papone-di-rey-feat', '2013', 'House', 'Germany / Argentina'),
(8, 'Ickar Flyer & Alice Phoebe Lou', 'The Devil His Sweetheart', 'https://www.youtube.com/watch?v=txiyCPXN0nE', '2013', 'Germany / South Africa', 'Singer/Songwriter / Dub'),
(9, 'Koudlam', 'See you all', 'https://www.youtube.com/watch?v=9ME8ISbP5iI', '2009', 'France', 'Electro'),
(10, '1000 Robota', 'Diese Brille', 'https://www.youtube.com/watch?v=pRMJ8kCMiz4', '2008', 'Germany', 'Indie / Punk-Rock / Post-Punk'),
(11, '1000 Robota', 'Hamburg brennt', 'https://www.youtube.com/watch?v=gl6yeBxm6P8', '2008', 'Germany', 'Indie / Punk-Rock / Post-Punk'),
(12, 'FKA Twigs', 'Hide', 'https://vimeo.com/83812313', '2014', 'UK', 'Post-RNB'),
(13, 'MC Fitti', 'SpÃ¤ti', 'https://www.youtube.com/watch?v=AQa2j2MnnRw', '2013', 'Germany', 'Rap'),
(14, 'Theo Parrish', 'Soul Control', 'https://www.youtube.com/watch?v=ixKSHqMFKj0', '2007', 'USA', 'House'),
(15, 'Alpines', 'Oasis (Mr. Mitch Remix)', 'https://www.youtube.com/watch?v=3pw_UO-VHVQ', '2014', 'UK', 'Dub / Grimy'),
(16, 'Lunice', 'Can''t wait to', 'https://www.youtube.com/watch?v=wv70IhlW5D4', '2012', 'Canada', 'Bass'),
(17, 'Unmap', 'When to lead and when to follow @Berlin Sessions (Live)', 'https://www.youtube.com/watch?v=r_-qAO-VJAY', '2013', 'Germany', 'Indietronic / Electronica / Singer/Songwriter'),
(18, 'Mine', 'Ziehst du mit (feat. Fatoni)', 'https://www.youtube.com/watch?v=QhICvxqSSDI', '2014', 'Germany', 'Rap / Singer/Songwriter / Neo-Chanson'),
(19, 'Mine', 'Der Mond lacht (Live)', 'https://www.youtube.com/watch?v=sdiFnZL6Tio', '2013', 'Germany', 'Singer/Songwriter / Neo-Chanson'),
(20, 'Lyr1c (=CRO)', 'What', 'https://www.youtube.com/watch?v=7kVtIb7Sj1U', '2009', 'Germany', 'Rap'),
(21, 'Tanner Ross & Slow Hands', 'All the same (Original Mix)', 'https://www.youtube.com/watch?v=l6dt7_Qcpow', '2013', 'USA', 'House'),
(22, 'Jayteehazard', 'Solis', 'https://soundcloud.com/jaytee_hazard/solis-original-mix-1', '2014', 'Australia', 'Bass / Instrumental HipHop'),
(23, 'Zola Blood', 'Grace', 'https://www.youtube.com/watch?v=sgBCSzzePvk', '2014', 'UK', 'Bass / Dub / Electronica / Indie'),
(24, 'Yeasayer', 'Ambling Alp', 'https://www.youtube.com/watch?v=_25bsKcXw5o', '2009', 'USA', 'Indie-Rock'),
(25, 'Jeremih', 'Fuck U All The Time (Shlohmo Remix)', 'https://soundcloud.com/shlohmo/jeremih-fuck-u-all-the-time', '2012', 'USA', 'Bass'),
(26, 'Jamie T', 'Don''t You Find', 'https://www.youtube.com/watch?v=-tmoaFAT108', '2014', 'UK', 'Singer/Songwriter / Bass'),
(27, 'Stereotyp & Soothsayer', 'Dub Club Track', 'https://www.youtube.com/watch?v=2VexVh8smsw', '2000', 'Austria', 'Dub'),
(28, 'Austra', 'Beat And The Pulse', 'https://www.youtube.com/watch?v=emHAfLWqbnA', '2010', 'Canada', 'New Wave / Electro / Bass'),
(29, 'Ricardo Villalobos', 'Fizheuer Zieheuer (37min Edit)', 'https://www.youtube.com/watch?v=H8_BAoVwoaM', '2006', 'Chile / Germany', 'Minimal Techno'),
(30, 'Detachments', 'Circles (Martyn Remix) ', 'https://www.youtube.com/watch?v=UzS7Gvn7jJ0', '2010', 'UK / Germany', 'Dub / Minimal / Indie');